// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYNDEuz-bqIbRpqAEZtuuUSo4Xc_akoQg',
    appId: '1:420167176415:web:331f463c34bc9fe9bf596a',
    messagingSenderId: '420167176415',
    projectId: 'u-chat-me-6febd',
    authDomain: 'u-chat-me-6febd.firebaseapp.com',
    storageBucket: 'u-chat-me-6febd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJZJloYznqdPI1CeC7kFdW3kSnUrcJEo',
    appId: '1:420167176415:android:ed7cc8a78ed7dffcbf596a',
    messagingSenderId: '420167176415',
    projectId: 'u-chat-me-6febd',
    storageBucket: 'u-chat-me-6febd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKPkXEAoj38JeRc5kXNiWaDwneJ6k_lUQ',
    appId: '1:420167176415:ios:5df8529a516c75acbf596a',
    messagingSenderId: '420167176415',
    projectId: 'u-chat-me-6febd',
    storageBucket: 'u-chat-me-6febd.appspot.com',
    androidClientId: '420167176415-7r1pultist8ufcv7m149alg0vq9a3235.apps.googleusercontent.com',
    iosClientId: '420167176415-j8ua347h7cbngfuk7h8qcj9mg0eqb0vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.uChatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKPkXEAoj38JeRc5kXNiWaDwneJ6k_lUQ',
    appId: '1:420167176415:ios:5df8529a516c75acbf596a',
    messagingSenderId: '420167176415',
    projectId: 'u-chat-me-6febd',
    storageBucket: 'u-chat-me-6febd.appspot.com',
    androidClientId: '420167176415-7r1pultist8ufcv7m149alg0vq9a3235.apps.googleusercontent.com',
    iosClientId: '420167176415-j8ua347h7cbngfuk7h8qcj9mg0eqb0vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.uChatMe',
  );
}
